<div>
投稿用ページ
<hr>
<form method="POST" action 
店名：<input type="text" property="shop_name"></input><br><br>
都道府県：
<select>
<option property="prefecture" value="1">東京</option>
</select>
<br><br>
市町村：<input type="text" property="town"></input><br><br>
番地：<input type="text" property="house_num"></input><br><br>
ビル名等：<input type="text" property="building"></input><br><br>
コメント：<textarea property="comment"></textarea>
</div>

